version: "3.4"

services:
  # node:
  #   build:
  #     context: "node/"
  #   image: node-app
  #   env_file:
  #     - "./node/.env"
  #   ports:
  #     - 3000:3000

  angular:
    build:
      context: "/"
    image: simple-app
    env_file:
      - "./.env"
    ports:
      - 4201:3000