version: "3.4"

services:
  # node:
  #   build:
  #     context: "node/"
  #   image: node-app
  #   env_file:
  #     - "./node/.env"
  #   ports:
  #     - 3000:3000

  e2e_test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simple_e2e_app
    ports:
      - 4201:4201
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock