name: Pipeline CI/CD - push para o origin

on:
  push:
    branches:
      'master'
env:
  RESOURCE-GROUP: RGPROJETOTCC2023
  LOCATION: eastus2
  TEMPLATE-FILE: .azure/template.bicep
  TEMPLATE-FILE-ACR: .azure/acr_project.bicep
  SUBSCRIPTION-ID: 9157087b-28a6-4c6b-a615-c827504e377a
  WEBAPP-NAME: projeto-tcc-2023

jobs:
  setup:
    name: Testando aplicação e criando artefato
    runs-on: ubuntu-latest   
    steps:
    - name: Checando repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Instalando pnpm
      uses: pnpm/action-setup@v2.2.1
      with:
        version: "7.x"
    - name: Instalando NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
      
    - name: Instalando Dependencias
      run: pnpm install
      
#     - name: Buildando projeto
#       run: pnpm run build:all
      
#     - name: Publicando o projeto
#       run: pnpm -r publish --no-git-checks
      
    - name: artefato webapp
      uses: actions/upload-artifact@v2
      with:
        name: artefato-app
        path:  ${{ env.TEMPLATE-FILE }}

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE-ACR }}
  
  deploy:
    runs-on: ubuntu-latest
    needs: setup

    steps:
        
      #Download do arquivo bicep
      - name: Download artifato template bicep
        uses: actions/download-artifact@v3
        with:
          name: bicep-template
          path: bicep-template

      #Download do arquivo bicep
      - name: Download artifato app
        uses: actions/download-artifact@v3
        with:
          name: artefato-app
          path: artefato-app

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PROJETO_TCC_SECRETS}}

      - name: deploy acr
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/acr_project.bicep
          failOnStdErr: false
          deploymentOutputs: 'outputJson'
          
      - name: Azure PowerShell Action
        uses: Azure/powershell@v1
        with:
    # Specify the Az PowerShell script here.
          inlineScript: |
            az acr login --name acrprojetoufam |
            az acr show --name acrprojetoufam --query loginServer --output table --subscription  ${{ env.SUBSCRIPTION-ID }}
          azPSVersion: "latest"
          
      - name: Build the frontend image and push it to ACR
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acrprojetoufam.azurecr.io/teste:latest
          file: .azure/Dockerfile

      - name: deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/template.bicep
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false 
            

      # - name: Publish Website to WebApp
      #   uses: Azure/webapps-deploy@v2
      #   with:
      #     app-name: ${{ env.WEBAPP-NAME  }}
      #     package: artefato1-app  
                

        
    
        
  
