name: Pipeline CI/CD - push para o origin

on:
  push:
    branches:
      'master'

jobs:
  setup:
    name: Testando aplicação e criando artefato
    runs-on: ubuntu-latest   
    steps:
    - name: Checando repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
  
