name: Pipeline CI/CD - push para o origin

on:
  push:
    branches:
      'master'
env:
  RESOURCE-GROUP: RGPROJETOTCC2023
  LOCATION: eastus2
  TEMPLATE-FILE: .azure/template.bicep
  SUBSCRIPTION-ID: 9157087b-28a6-4c6b-a615-c827504e377a
  WEBAPP-NAME: projeto-tcc-2023

jobs:
  setup:
    name: Testando aplicação e criando artefato
    runs-on: ubuntu-latest   
    steps:
    - name: Checando repositorio
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Instalando pnpm
      uses: pnpm/action-setup@v2.2.1
      with:
        version: "7.x"
    - name: Instalando NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
      
    - name: Instalando Dependencias
      run: pnpm install
      
    - name: Buildando projeto
      run: pnpm run build:all
      
    - name: Publicando o projeto
      run: pnpm -r publish --no-git-checks
      
    - name: artefato
      uses: actions/upload-artifact@v2
      with:
        name: artefato1-app
        path: dist/apps/simple-app

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE }}

        
    
        
  
